#
#   При каком онлайне будет происходить перезапуск.
#
online: 3

#
#   Минуты после захода нужного количества игроков.
#
time: 10

#
#   Сообщение перед перезапуском.
#
restart-coming-message: "Перезапуск произойдёт через 5 сек."

#
#   Сообщение при кике во время перезапуска.
#
kick-restart-event: "Сервер перезапускается!"